<?php

/**
 * @file
 * Contains functionality for node admin.
 */

/**
 *  Implements hook_menu().
 */
function node_admin_menu() {
  $items = array();
  $types = node_type_get_types();
  foreach ($types as $type => $type_object) {
    $items['admin/content/node/'. $type] = array(
      'title' => check_plain($type),
      'description' => 'Administer content.',
      'page callback' => 'node_admin_page',
      'page arguments' => array($type),
      'access arguments' => array('administer ' . $type . ' node'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'node_admin.pages.inc',
    );
  }
  return $items;
}

/**
 *  Implements hook_menu_alter().
 */
function node_admin_menu_alter(&$items) {
  $items['admin/content/node_admin']['access callback'] = 'user_access';
  $items['admin/content/node_admin']['access arguments'] = array('administer node admin module');
}

/**
 * Implements hook_permission().
 */
function node_admin_permission() {
  $permissions = array();
  $permissions['administer node admin module'] = array(
    'title' => t('Administer node admin module'),
    'description' => t('Administer the functionality of node admin module'),
 );
  $types = node_type_get_types();
  foreach ($types as $type => $type_object) {
    $permissions['administer ' . $type . ' node'] = array(
      'title' => t('Administer @type', array('@type' => $type)),
      'description' => t('Administer the @type nodes', array('@type' => $type)),
    );
  }
  return $permissions;
}

/**
 * Implements hook_views_api().
 */
function node_admin_views_api() {
  return array(
    'api' => 3,
  );
}
